# Generated by Django 5.1.1 on 2024-10-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasense_api', '0002_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='total_columns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
    ]
