# Generated by Django 5.1.1 on 2024-10-07 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasense_api', '0003_userdata_total_columns_alter_userdata_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresults',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
