# Generated by Django 5.1.1 on 2024-10-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasense_api', '0004_userresults_generated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='user',
        ),
    ]
